version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: florestal
      POSTGRES_PASSWORD: florestal
      POSTGRES_DB: florestal
    ports:
      - "5432:5432"

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
